# Note: This file is in a separate repository and its not currently seen as worth while
# to move it to the main repository. It is used for CI/CD of AWS CloudFormation templates.
# Therefore:
# 1. it doesn't use the self-hosted agent pool which requires scripts declared in the main repository.
#
# Also note that it uses the ImageId specified in the template. This needs to be updated
# manually when the image is updated. It would be better to pick up the image id from, say
# the published image artefacts. But its about template validation, not image validation.
# Therefore the image id is unimportant.
variables:
- name: captureStackOutputs
  value: asJSON
- name: CookbooksSource
  value: $(Build.Repository.LocalPath)\cookbooks
- name: CookbooksSource1
  value: c:\lansa
- name: TemplateS3Namespace
  value:
- name: regionName
  value: ap-southeast-2
- group: "Default Branch"
- group: "Template Parameters"
- group: "VPC ap-southeast-2"
- group: "ImageVersion"
- group: "Logins"
resources:
  repositories:
  - repository: self
    type: git
    ref: support/scalable
jobs:
- job: Job_2
  displayName: 'Test Template CI'
  timeoutInMinutes: 360
  pool:
    vmImage: windows-latest

  steps:
  - checkout: self

  - template: AWSValidateTemplates.yml
    parameters:
      sourceFolder: CloudFormationWindows
      targetFolder: templates/$(CookbooksBranch)

  - task: AmazonWebServices.aws-vsts-tools.AWSPowerShellModuleScript.AWSPowerShellModuleScript@1
    displayName: 'Delete existing stack : BakingDP'
    inputs:
      awsCredentials: $(awsCredentials)
      regionName: $(regionName)
      scriptType: inline
      inlineScript: >-
        try{

        Get-CFNStack -StackName $(stackname)

        Remove-CFNStack -StackName $(stackname) -Force

        $count =0

        while($count -lt 20){
           try{
                 Get-CFNStack -StackName $(stackname)
                 Start-Sleep -Seconds 200
                 Write-Host "Deleting stack"
                 $count = $count +1
               }
            catch{
                 Write-Host "Stack Deleted"
                 break
                  }
             }

        Write-Host "Stack deleted"

        }

        catch{

        Write-Host "There is no stack or it was deleted"

        }

  - task: AmazonWebServices.aws-vsts-tools.CloudFormationCreateOrUpdateStack.CloudFormationCreateOrUpdateStack@1
    name: ''
    displayName: 'Deploy BakingDP-TemplateTest stack'
    inputs:
      awsCredentials: $(awsCredentials)
      regionName: $(regionName)
      stackName: $(stackname)
      templateSource: s3
      templateFile: CloudFormationWindows/lansa-master-win.cfn.template
      s3BucketName: $(BucketNamePreview)
      s3ObjectKey: templates/$(CookbooksBranch)/lansa-master-win.cfn.template
      templateParametersSource: inline
      templateParameters: |
        [{
            "ParameterKey": "$(DBPasswordKey)",
            "ParameterValue": "$(DBPasswordValue)"
        }, {
            "ParameterKey": "$(WebPasswordKey)",
            "ParameterValue": "$(WebPasswordValue)"
        }, {
            "ParameterKey": "$(KeyNameKey)",
            "ParameterValue": "$(KeyNameValue)"
        }, {
            "ParameterKey": "$(RemoteAccessLocationKey)",
            "ParameterValue": "$(RemoteAccessLocationValue)"
        },{
            "ParameterKey": "10LansaGitRepoBranch",
            "ParameterValue": "$(CookbooksBranch)"
        },{
            "ParameterKey": "UpdateManagementScripts",
            "ParameterValue": "Yes"
        }, {
            "ParameterKey": "$(LansaMSIKey)",
            "ParameterValue": "$(msiURLv16)"
        }, {
            "ParameterKey": "CurrentVPC",
            "ParameterValue": "$(CurrentVPC)"
        }, {
            "ParameterKey": "AvailabilityZones",
            "ParameterValue": "$(AvailabilityZones)"
        }, {
            "ParameterKey": "NumberOfAZs",
            "ParameterValue": "$(NumberOfAZs)"
        }, {
            "ParameterKey": "DBSubnetGroupName",
            "ParameterValue": "$(DBSubnetGroupName)"
        }, {
            "ParameterKey": "ELBSubnetIds",
            "ParameterValue": "$(ELBSubnetIds)"
        }, {
            "ParameterKey":  "03DBUsername",
            "ParameterValue": "$(03DBUsername)"
        }, {
            "ParameterKey": "MPS3KeyPrefix",
            "ParameterValue": "templates/$(CookbooksBranch)$(TemplateS3Namespace)/"
        }]
      tags: usage=temp-test
      onFailure: DO_NOTHING
      outputVariable: deploymentOutput
      captureStackOutputs: $(captureStackOutputs)
      captureAsSecuredVars: false
      timeoutInMins: 100

  - task: AmazonWebServices.aws-vsts-tools.AWSPowerShellModuleScript.AWSPowerShellModuleScript@1
    displayName: 'Run URL Tests'
    inputs:
      awsCredentials: $(awsCredentials)
      regionName: $(regionName)
      filePath: scripts\TestCFNDeployment.ps1
      arguments:
        -Gatestack $(stackname)
        -DisableIntegratorTest

  - task: AmazonWebServices.aws-vsts-tools.AWSPowerShellModuleScript.AWSPowerShellModuleScript@1
    displayName: 'Test Image Version w19d-15-0 Prod'
    condition: or(succeeded(), eq(variables['ForceDeploy'], 'True'))
    inputs:
      awsCredentials: $(awsCredentials)
      regionName: $(regionName)
      filePath: scripts/AlternateImageVersion.ps1
      arguments:
        -Gatestack $(stackname)
        -Gateversion "w19d-15-0-$(VersionText-TemplateCI)"
        -Region 'ap-southeast-2'

  - task: CopyFiles@2
    displayName: 'Copy Files to Artifact Staging Directory'
    inputs:
      SourceFolder: CloudFormationWindows
      Contents: '*.template'
      TargetFolder: $(build.artifactstagingdirectory)
      CleanTargetFolder: true
      OverWrite: true

  - task: ArchiveFiles@2
    displayName: 'Zip Files in Staging Directory'
    inputs:
      rootFolderOrFile: $(build.artifactstagingdirectory)
      sevenZipCompression: 5
      archiveFile: $(Build.ArtifactStagingDirectory)/AwsTemplates.zip
      verbose: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Solution Template Artifact'
    inputs:
      ArtifactName: Solution Template
      FileCopyOptions: ''
...