variables:
- name: captureStackOutputs
  value: asJSON
- name: CookbooksSource
  value: $(Build.Repository.LocalPath)\cookbooks
- name: CookbooksSource1
  value: c:\lansa
- name: regionName
  value: ap-southeast-2
- group: "Default Branch"
- group: "Template Parameters"
- group: "VPC ap-southeast-2"
- group: "ImageVersion"
- group: "Logins"
resources:
  repositories:
  - repository: self
    type: git
    ref: support/scalable
jobs:
- job: Job_2
  displayName: 'Test Template CI'
  timeoutInMinutes: 360
  pool:
    vmImage: windows-2022
  steps:
  - checkout: self
  - task: AmazonWebServices.aws-vsts-tools.S3Upload.S3Upload@1
    displayName: 'S3 Upload: lansa'
    inputs:
      awsCredentials: $(awsCredentials)
      regionName: $(regionName)
      bucketName: $(BucketNamePreview)
      sourceFolder: CloudFormationWindows
      globExpressions: >
        *.template
      targetFolder: templates/$(CookbooksBranch)
      filesAcl: public-read-write

  - task: AmazonWebServices.aws-vsts-tools.AWSPowerShellModuleScript.AWSPowerShellModuleScript@1
    displayName: 'Delete existing stack : BakingDP'
    inputs:
      awsCredentials: $(awsCredentials)
      regionName: $(regionName)
      scriptType: inline
      inlineScript: >-
        try{

        Get-CFNStack -StackName $(stackname)

        Remove-CFNStack -StackName $(stackname) -Force

        $count =0

        while($count -lt 20){
           try{
                 Get-CFNStack -StackName $(stackname)
                 Start-Sleep -Seconds 200
                 Write-Host "Deleting stack"
                 $count = $count +1
               }
            catch{
                 Write-Host "Stack Deleted"
                 break
                  }
             }

        Write-Host "Stack deleted"

        }

        catch{

        Write-Host "There is no stack or it was deleted"

        }

  - task: AmazonWebServices.aws-vsts-tools.CloudFormationCreateOrUpdateStack.CloudFormationCreateOrUpdateStack@1
    name: ''
    displayName: 'Deploy BakingDP-TemplateTest stack'
    inputs:
      awsCredentials: $(awsCredentials)
      regionName: $(regionName)
      stackName: $(stackname)
      templateSource: s3
      templateFile: CloudFormationWindows/lansa-master-win.cfn.template
      s3BucketName: $(BucketNamePreview)
      s3ObjectKey: templates/$(CookbooksBranch)/lansa-master-win.cfn.template
      templateParametersSource: inline
      templateParameters: |
        [{
            "ParameterKey": "$(DBPasswordKey)",
            "ParameterValue": "$(DBPasswordValue)"
        }, {
            "ParameterKey": "$(WebPasswordKey)",
            "ParameterValue": "$(WebPasswordValue)"
        }, {
            "ParameterKey": "$(KeyNameKey)",
            "ParameterValue": "$(KeyNameValue)"
        }, {
            "ParameterKey": "$(RemoteAccessLocationKey)",
            "ParameterValue": "$(RemoteAccessLocationValue)"
        },{
            "ParameterKey": "10LansaGitRepoBranch",
            "ParameterValue": "$(CookbooksBranch)"
        },{
            "ParameterKey": "UpdateManagementScripts",
            "ParameterValue": "Yes"
        }, {
            "ParameterKey": "$(LansaMSIKey)",
            "ParameterValue": "$(msiURLLatest)"
        }, {
            "ParameterKey": "CurrentVPC",
            "ParameterValue": "$(CurrentVPC)"
        }, {
            "ParameterKey": "AvailabilityZones",
            "ParameterValue": "$(AvailabilityZones)"
        }, {
            "ParameterKey": "NumberOfAZs",
            "ParameterValue": "$(NumberOfAZs)"
        }, {
            "ParameterKey": "DBSubnetGroupName",
            "ParameterValue": "$(DBSubnetGroupName)"
        }, {
            "ParameterKey": "ELBSubnetIds",
            "ParameterValue": "$(ELBSubnetIds)"
        }, {
            "ParameterKey":  "03DBUsername",
            "ParameterValue": "$(03DBUsername)"
        }]
      tags: usage=temp-test
      onFailure: DO_NOTHING
      outputVariable: deploymentOutput
      captureStackOutputs: $(captureStackOutputs)
      captureAsSecuredVars: false
      timeoutInMins: 100

  - task: AmazonWebServices.aws-vsts-tools.AWSPowerShellModuleScript.AWSPowerShellModuleScript@1
    displayName: 'Run URL Tests'
    inputs:
      awsCredentials: $(awsCredentials)
      regionName: $(regionName)
      arguments: -Gatestack $(stackname)
      filePath: scripts\TestCFNDeployment.ps1

  - task: AmazonWebServices.aws-vsts-tools.AWSPowerShellModuleScript.AWSPowerShellModuleScript@1
    displayName: 'Test Image Version w19d-15-0 Prod'
    condition: or(succeeded(), eq(variables['ForceDeploy'], 'True'))
    inputs:
      awsCredentials: $(awsCredentials)
      regionName: $(regionName)
      arguments: -Gatestack $(stackname) -Gateversion "w19d-15-0-$(VersionText-TemplateCI)" -Region 'ap-southeast-2'
      filePath: scripts/AlternateImageVersion.ps1

  - task: CopyFiles@2
    displayName: 'Copy Files to Artifact Staging Directory'
    inputs:
      SourceFolder: CloudFormationWindows
      Contents: '*.template'
      TargetFolder: $(build.artifactstagingdirectory)
      CleanTargetFolder: true
      OverWrite: true

  - task: ArchiveFiles@2
    displayName: 'Zip Files in Staging Directory'
    inputs:
      rootFolderOrFile: $(build.artifactstagingdirectory)
      sevenZipCompression: 5
      archiveFile: $(Build.ArtifactStagingDirectory)/AwsTemplates.zip
      verbose: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Solution Template Artifact'
    inputs:
      ArtifactName: Solution Template
      FileCopyOptions: ''
...